import Head from 'next/head'
import type { AppProps } from 'next/app'
import Layout from '../layout'
import '../styles/globals.scss'

const MyApp = ({ Component, pageProps }: AppProps) => (
  <>
    <Head>
      <title>React và những người bạn</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Layout>
      <Component {...pageProps} />
    </Layout>
  </>
  )

export default MyApp
